server:
    port: 8081

spring:
    application:
        name: examplo-clean-arch
    data:
        mongodb:
            uri: mongodb://localhost:57119/clean-arch-spring
#            uri: ${DB_MONGODB_URI}
        jackson:
            property-naming-strategy: SNAKE_CASE

